name: Dependency based workflows


on:
  push:
    branches:
      - main


jobs:
  get_thirsty:
    runs-on: ubuntu-latest
    steps:
      - name: get thirsty first
        run: echo "I am thirsty"
        shell: bash
  need_water:
    runs-on: ubuntu-latest
    steps:
      - name: then need water
        run: echo "I got water but need glass too"
        shell: bash
  get_glass:
    runs-on: ubuntu-latest
    steps:
      - name: get glass now
        run: echo "I got glass now"
        shell: bash
  drink_water:
    runs-on: ubuntu-latest
    needs:
      - get_thirsty
      - need_water
      - get_glass
    steps:
      - name: drink water now
        run: echo "I drink water now"
        shell: bash
  feeling_good:
    runs-on: ubuntu-latest
    needs:
            - drink_water
            - eat_food
    steps:
        - name: All is well
          run: echo "All is well, I am no more thirsty"
          shell: bash

  must_hungry:
    runs-on: ubuntu-latest
    steps:
        - name: i am hungry
          run: echo "I am hungry"
          shell: bash
  get_food:
    runs-on: ubuntu-latest
    needs:
        - must_hungry
    steps:
        - name: get food
          run: echo "i got food man!"
          shell: bash
  eat_food:
    runs-on: ubuntu-latest
    needs:
        - must_hungry
        - get_food
    steps:
        - name: eating food
          run: echo "Eating food!"
          shell: bash
